### ISSUE TITLE
spring-boot-configuration-processor added but no changes to the folder of target

### ISSUE THREAD

**Issue by roy2020china** [bclozel/issues-dashboard#8] opened 2019-03-07 23:52 UTC
## Problem description: dependency "spring-boot-configuration-processor" added, but no changes to the folder of target
![screen shot 2019-03-08 at 07 50 17](https://user-images.githubusercontent.com/10363512/53997381-ed053a80-4176-11e9-81d1-ebebde09ca02.png)
## my POM.XML
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.3.RELEASE</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.zhangbing</groupId>
	<artifactId>demo2</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo2</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>
		<!-- <dependency> <groupId>org.flywaydb</groupId> <artifactId>flyway-core</artifactId> 
			</dependency> -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
			<!-- <version>2.1.2.RELEASE</version> -->
		</dependency>


		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.flywaydb</groupId>
				<artifactId>flyway-maven-plugin</artifactId>
				<!-- <version>5.2.4</version> -->
			</plugin>
		</plugins>
	</build>

</project>

```

**Comment by bclozel** [comment] 2019-03-11 17:41
It seems your application is not using the current repository, so this makes it impossible for me to reproduce the problem. Could you provide a link to something I can clone and run?

In the meantime, please avoid setting versions manually as they are managed by Spring Boot (especially for the Spring projects in general).

Maybe this is a problem linked to your IDE, since the whole folder seems to be empty?
You could try the following on the command line:

```
$ ./mvnw package
$ ls target/classes/META-INF
spring-configuration-metadata.json
```

**Comment by jacGJ** [comment] 2019-07-15 07:18
![image](https://user-images.githubusercontent.com/32384721/61200367-bc7c7100-a713-11e9-81b8-613e7183350d.png)
it is different from mime!
![image](https://user-images.githubusercontent.com/32384721/61200117-fb5df700-a712-11e9-9014-3d8c89f64a55.png)
can you tell me why? how can I do? thanks!

**Comment by bclozel** [comment] 2019-07-15 07:23
@jacGJ duplicate of #11 
@roy2020china closing this issue as you didn't provide any feedback.

**Closed as completed by bclozel** 2019-07-15 07:23 UTC

**Comment by jacGJ** [comment] 2019-07-15 07:26
thanks




------------------ 原始邮件 ------------------
发件人: "Brian Clozel"<notifications@github.com>;
发送时间: 2019年7月15日(星期一) 下午3:23
收件人: "bclozel/issues-dashboard"<issues-dashboard@noreply.github.com>;
抄送: "wsldctds"<418037264@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [bclozel/issues-dashboard] spring-boot-configuration-processoradded but no changes to the folder of target (#8)




@jacGJ duplicate of #11
 @roy2020china closing this issue as you didn't provide any feedback.
